"""empty message

Revision ID: 15fa7d06e771
Revises: 4c55638678ca
Create Date: 2020-09-19 17:22:26.699694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15fa7d06e771'
down_revision = '4c55638678ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('router_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'devices', 'routers', ['router_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'router_id')
    # ### end Alembic commands ###
